services:
  ${NODE_NAME}:
    image: ${IMAGE}
    restart: always
    env_file:
      - ${ENV_FILE}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PORT}:${PORT}
    command: ["python", "/app/api-containers/app2.py"]




