version: "3"

services:
  server:
    image: python:3.10-slim
    restart: always
    env_file:
      - ${}.env
    container_name: aggregator_server_${PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
        - .:/app
    command: ["python", "app.py", "--env-file", "/app/${}.env"]