version: "3"

services:
  server:
    image: edgefl:latest
    restart: always
    env_file:
      - /home/miguelcse121/PycharmProjects/Anylog-Edgelake-Federated-Learning-Platform/edgefl/env_files/mnist-docker/mnist-agg.env
    container_name: aggregator_server_8080
    ports:
      - 8080:8080
    volumes:
      - ./edgefl:/app/edgefl  # Only mount specific directories
      - ./api-containers:/app/api-containers
    command: ["python", "/app/api-containers/app2.py", "--env-file", "/app/edgefl/env_files/mnist-docker/mnist-agg.env"]