services:
  ${NODE_NAME}:
#    image: python:3.10-slim
    restart: always
    env_file:
      - /platform_${NODE_NAME}.env
      - ${NODE_NAME}.env
    container_name: ${NODE_NAME}
    stdin_open: true
    tty: true
#    ports:
#      - ${PORT}:${PORT}
#    volumes:
#        - ${NODE_NAME}--platform:/app/${NODE_NAME}
#        - ./aggregator_server_${PORT}.env:/app/aggregator_server_${PORT}.env
#    command: sh -c "uvicorn main:app --reload --port=${PORT} --host=0.0.0.0"