services:
  ${CONTAINER_NAME}:
    image: ${IMAGE}
    restart: always
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONTAINER_NAME}_data:/app/data
    command: [
      "python",
      "/app/api-containers/app.py",
      "--env-file", "${ENV_FILE}",
      "--port", "${PORT}"
    ]

volumes:
  ${CONTAINER_NAME}_data: